title: Roman's Blog
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about any kind of technical
  topics (integration, messaging, developing, ...).
permalink: /:year/:month/:day/:title:output_ext
baseurl: ""
url: "http://blog.jromanmartin.io"
site-twitter: jromanmartin

# Author Settings
author: Roman Martin
author-img: roman-martin.png
about-author: >
  Father, Husband, Friend, Runner, Curious, Red Hatter, Developer, Architect (in any order). Principal Middleware Architect at Red Hat.
  Focusing on AppDev, Integration, Cloud Native, and development lifecycle.
  Always learning.
social-twitter: jromanmartin
social-github: rmarting
social-linkedin: jromanmartin
social-email: jromanmartin@gmail.com

navigation_pages:
  - cheat-sheets.md
  - articles.md
  - meetups.md
  - CONTRIBUTING.md
  - about.md

# Disqus
discus-identifier: jromanmartin

# Google Analytics
analytics: UA-179063099-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
